CREATE TABLE `ContactCampaignConsent` (
  `id` CHAR(36) NOT NULL,
  `companyId` CHAR(36) NOT NULL,
  `contactId` CHAR(36) NOT NULL,
  `updatedByMembershipId` CHAR(36) NULL,
  `status` ENUM('OPTED_IN', 'OPTED_OUT') NOT NULL,
  `source` ENUM('MANUAL', 'INBOUND_KEYWORD') NOT NULL DEFAULT 'MANUAL',
  `note` VARCHAR(500) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ContactCampaignConsent_contactId_key` (`contactId`),
  INDEX `ContactCampaignConsent_companyId_status_updatedAt_idx` (`companyId`, `status`, `updatedAt`),
  INDEX `ContactCampaignConsent_updatedByMembershipId_updatedAt_idx` (`updatedByMembershipId`, `updatedAt`),
  CONSTRAINT `ContactCampaignConsent_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `Company`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContactCampaignConsent_contactId_fkey` FOREIGN KEY (`contactId`) REFERENCES `Contact`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ContactCampaignConsent_updatedByMembershipId_fkey` FOREIGN KEY (`updatedByMembershipId`) REFERENCES `CompanyMembership`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `Campaign` (
  `id` CHAR(36) NOT NULL,
  `companyId` CHAR(36) NOT NULL,
  `segmentId` CHAR(36) NOT NULL,
  `whatsappConnectionId` CHAR(36) NOT NULL,
  `createdByMembershipId` CHAR(36) NOT NULL,
  `name` VARCHAR(160) NOT NULL,
  `body` TEXT NOT NULL,
  `status` ENUM('DRAFT','RUNNING','COMPLETED','CANCELLED','FAILED') NOT NULL DEFAULT 'DRAFT',
  `ratePerMinute` INTEGER NOT NULL DEFAULT 6,
  `windowStartAt` DATETIME(3) NOT NULL,
  `windowEndAt` DATETIME(3) NOT NULL,
  `audienceSnapshotAt` DATETIME(3) NULL,
  `segmentDefinition` JSON NULL,
  `segmentContacts` INTEGER NOT NULL DEFAULT 0,
  `eligibleRecipients` INTEGER NOT NULL DEFAULT 0,
  `optedOutRecipients` INTEGER NOT NULL DEFAULT 0,
  `unknownConsent` INTEGER NOT NULL DEFAULT 0,
  `startedAt` DATETIME(3) NULL,
  `completedAt` DATETIME(3) NULL,
  `cancelledAt` DATETIME(3) NULL,
  `error` VARCHAR(1000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Campaign_companyId_status_updatedAt_idx` (`companyId`, `status`, `updatedAt`),
  INDEX `Campaign_segmentId_createdAt_idx` (`segmentId`, `createdAt`),
  INDEX `Campaign_whatsappConnectionId_status_idx` (`whatsappConnectionId`, `status`),
  INDEX `Campaign_createdByMembershipId_createdAt_idx` (`createdByMembershipId`, `createdAt`),
  CONSTRAINT `Campaign_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `Company`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `Campaign_segmentId_fkey` FOREIGN KEY (`segmentId`) REFERENCES `ContactSegment`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Campaign_whatsappConnectionId_fkey` FOREIGN KEY (`whatsappConnectionId`) REFERENCES `WhatsAppConnection`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `Campaign_createdByMembershipId_fkey` FOREIGN KEY (`createdByMembershipId`) REFERENCES `CompanyMembership`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `CampaignRecipient` (
  `id` CHAR(36) NOT NULL,
  `campaignId` CHAR(36) NOT NULL,
  `contactId` CHAR(36) NOT NULL,
  `status` ENUM('PENDING','PROCESSING','SENT','FAILED','SUPPRESSED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `snapshotName` VARCHAR(190) NOT NULL,
  `snapshotRemoteJid` VARCHAR(190) NOT NULL,
  `exclusionReason` VARCHAR(80) NULL,
  `plannedFor` DATETIME(3) NULL,
  `claimedAt` DATETIME(3) NULL,
  `sentAt` DATETIME(3) NULL,
  `externalId` VARCHAR(190) NULL,
  `ticketId` CHAR(36) NULL,
  `messageId` CHAR(36) NULL,
  `error` VARCHAR(1000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `CampaignRecipient_campaignId_contactId_key` (`campaignId`, `contactId`),
  INDEX `CampaignRecipient_campaignId_status_plannedFor_idx` (`campaignId`, `status`, `plannedFor`),
  INDEX `CampaignRecipient_contactId_createdAt_idx` (`contactId`, `createdAt`),
  INDEX `CampaignRecipient_status_plannedFor_idx` (`status`, `plannedFor`),
  CONSTRAINT `CampaignRecipient_campaignId_fkey` FOREIGN KEY (`campaignId`) REFERENCES `Campaign`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CampaignRecipient_contactId_fkey` FOREIGN KEY (`contactId`) REFERENCES `Contact`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `CampaignEvent` (
  `id` CHAR(36) NOT NULL,
  `companyId` CHAR(36) NOT NULL,
  `campaignId` CHAR(36) NOT NULL,
  `actorMembershipId` CHAR(36) NULL,
  `type` ENUM('CREATED','UPDATED','STARTED','CANCELLED','COMPLETED','FAILED') NOT NULL,
  `metadata` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `CampaignEvent_companyId_createdAt_idx` (`companyId`, `createdAt`),
  INDEX `CampaignEvent_campaignId_createdAt_idx` (`campaignId`, `createdAt`),
  CONSTRAINT `CampaignEvent_companyId_fkey` FOREIGN KEY (`companyId`) REFERENCES `Company`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CampaignEvent_campaignId_fkey` FOREIGN KEY (`campaignId`) REFERENCES `Campaign`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `CampaignEvent_actorMembershipId_fkey` FOREIGN KEY (`actorMembershipId`) REFERENCES `CompanyMembership`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
